// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csdbpewucfrdsefegljd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZGJwZXd1Y2ZyZHNlZmVnbGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDIxMDMsImV4cCI6MjA3MjkxODEwM30.3E1LJI3JIPLaNMd1BAsdUZGg8JACfy5lbAeXfk2lhHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});